version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=$DB_DATABASE
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - db:/var/lib/mysqldata

  mysqldb_testing:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=testing
      - MYSQL_USER=test
      - MYSQL_PASSWORD=123
    ports:
      - "3307:3306"  # Use a different port for the second database
    volumes:
      - db_testing:/var/lib/mysqldata

volumes:
  db:
  db_testing:
